name: OpenShift
env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: ''
  APP_NAME: ''
  APP_PORT: ''
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_REGISTRY_USER: ${{ github.actor }}
  IMAGE_REGISTRY_PASSWORD: ${{ github.token }}
  IMAGE_TAGS: ''
'on':
  workflow_dispatch: null
  push:
    branches:
    - main
jobs:
  crda-scan:
    uses: ./.github/workflows/crda.yml
    secrets:
      CRDA_KEY: ${{ secrets.CRDA_KEY }}
  openshift-ci-cd:
    name: Build and deploy to OpenShift
    runs-on: ubuntu-latest
    environment: production
    outputs:
      ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
      SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
    steps:
    - name: Check for required secrets
      uses: actions/github-script@v6
      with:
        script: "const secrets = {\n  OPENSHIFT_SERVER: `${{ secrets.OPENSHIFT_SERVER\
          \ }}`,\n  OPENSHIFT_TOKEN: `${{ secrets.OPENSHIFT_TOKEN }}`,\n};\n\nconst\
          \ GHCR = \"ghcr.io\";\nif (`${{ env.IMAGE_REGISTRY }}`.startsWith(GHCR))\
          \ {\n  core.info(`Image registry is ${GHCR} - no registry password required`);\n\
          }\nelse {\n  core.info(\"A registry password is required\");\n  secrets[\"\
          IMAGE_REGISTRY_PASSWORD\"] = `${{ secrets.IMAGE_REGISTRY_PASSWORD }}`;\n\
          }\n\nconst missingSecrets = Object.entries(secrets).filter(([ name, value\
          \ ]) => {\n  if (value.length === 0) {\n    core.error(`Secret \"${name}\"\
          \ is not set`);\n    return true;\n  }\n  core.info(`\u2714\uFE0F Secret\
          \ \"${name}\" is set`);\n  return false;\n});\n\nif (missingSecrets.length\
          \ > 0) {\n  core.setFailed(`\u274C At least one required secret is not set\
          \ in the repository. \\n` +\n    \"You can add it using:\\n\" +\n    \"\
          GitHub UI: https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository\
          \ \\n\" +\n    \"GitHub CLI: https://cli.github.com/manual/gh_secret_set\
          \ \\n\" +\n    \"Also, refer to https://github.com/redhat-actions/oc-login#getting-started-with-the-action-or-see-example\"\
          );\n}\nelse {\n  core.info(`\u2705 All the required secrets are set`);\n\
          }\n"
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Determine app name
      if: env.APP_NAME == ''
      run: 'echo "APP_NAME=$(basename $PWD)" | tee -a $GITHUB_ENV

        '
    - name: Determine image tags
      if: env.IMAGE_TAGS == ''
      run: 'echo "IMAGE_TAGS=latest ${GITHUB_SHA::12}" | tee -a $GITHUB_ENV

        '
    - name: Build from Dockerfile
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.APP_NAME }}
        tags: ${{ env.IMAGE_TAGS }}
        dockerfiles: './Dockerfile

          '
    - name: Push to registry
      id: push-image
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.IMAGE_REGISTRY_USER }}
        password: ${{ env.IMAGE_REGISTRY_PASSWORD }}
    - name: Install oc
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: 4
    - name: Log in to OpenShift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
    - name: Create and expose app
      id: deploy-and-expose
      uses: redhat-actions/oc-new-app@v1
      with:
        app_name: ${{ env.APP_NAME }}
        image: ${{ steps.push-image.outputs.registry-path }}
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
        port: ${{ env.APP_PORT }}
    - name: Print application URL
      env:
        ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
        SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}
      run: '[[ -n ${{ env.ROUTE }} ]] || (echo "Determining application route failed
        in previous step"; exit 1)

        echo

        echo "======================== Your application is available at: ========================"

        echo ${{ env.ROUTE }}

        echo "==================================================================================="

        echo

        echo "Your app can be taken down with: \"oc delete all --selector=''${{ env.SELECTOR
        }}''\""

        '
